spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/share
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /health
        healthCheckInterval: 15s
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  profiles:
     active: native
  security:
    user:
      password: admin
  application:
    name: config
server:
  port: 8888



